### ISSUE TITLE
Jupyter Lab Kernel fails when running basic_model

### ISSUE THREAD

**Issue by AJAX6255** [fastscape-lem/fastscape-demo#8] opened 2021-01-29 23:47 UTC
In the tutorial notebook titled "01_run_basic_model.ipynb"
whenever I run the cell that Runs the model
out_ds = in_ds.xsimlab.run(model=basic_model)
The jupyter lab kernel dies and I get the following error.
The kernel for tutorial/01_run_basic_model.ipynb appears to have died. It will restart automatically.

Have you any ideas of what might be causing this?
(I suspect you are going to say get the kernel logs and examine them.)
This seems odd, as the model setup and visualization cells work perfectly.
I am running locally on a conda installation having followed the fastscape-demo env instructions.

**Comment by AJAX6255** [comment] 2021-02-03 18:33
This issue repeated in "Conda" installs for both Windows and Ubuntu 20.4.
However when I use "Binder" - then ALL of the tutorials work properly.
So I would gather from this I have an insufficient local resource that causes the JupyterLab kernel to 
immediately fail when running "out_ds = in_ds.xsimlab.run(model=basic_model)".
I suspect this is related to insufficient local memory.

**Comment by benbovy** [comment] 2021-02-04 22:07
Thanks for reporting @AJAX6255, I'm using mostly MacOS so I may be missing some issues on other platforms. I'll try to see if I can reproduce your issue.

Did you install the conda packages from the environment file provided in the repository? Could you tell me which versions of `xarray-simlab`, `fastscape` and `fastscapelib-f2py` are installed on your machine? I wonder if this could be caused by some version mismatch.

> I suspect you are going to say get the kernel logs and examine them.

Not sure it would help. The kernel may die because of some segmentation fault or other crash happening in the underlying Fortran library.

**Comment by benbovy** [comment] 2022-06-23 09:22
FYI, some kernel die issues have been reported on Windows and were related to some conflict in openmp versions linked to some libraries installed in the environment, which were fixed after doing `conda install nomkl -c conda-forge`.

I'm going to close this issue. Do not hesitate to comment / re-open it if you still have troubles with unexpected kernel dies.

**Closed by benbovy** 2022-06-23 09:22 UTC
