### ISSUE TITLE
Something wrong when running those examples

### ISSUE THREAD

**Issue by minttan09** [fastscape-lem/fastscape-demo#12] opened 2021-08-23 13:51 UTC
I have met errors when plotting the output in those examples (e.g., fan, marine, dipping dyke, etc.). The model runs well, however, it shows "KeyError:'x' when we try to plot using hvplot. I have checked some possible causes, and have found that there are no output of x, y coordinates of the hillshade plot. Could it be the main cause? How to fix it? We have reinstall the same version of those plug-in components like those in the binder.

**Comment by benbovy** [comment] 2022-06-23 09:15
Sorry for the late reply @minttan09. Do you still have this error? I couldn't reproduce it, e.g., all the notebooks seem to run fine ([green CI job](https://github.com/fastscape-lem/fastscape-demo/runs/2132231209?check_suite_focus=true)).

**Comment by benbovy** [comment] 2023-09-27 08:49
Closing as I cannot reproduce it (all the notebooks seem to run fine in #15). @minttan09 feel free to reopen if the problem persists.

**Closed by benbovy** 2023-09-27 08:49 UTC
